export const BlankErrorMsg = "This Field Can't Be Blank";
export const InvalidLoginCredential = "Invalid Username or Password";
export const InvalidEmailError = "Invalid Email Id";
export const InvalidMobileError = "Invalid Mobile No.";

// created on 4 dec - priyanka 110 t0 130
export const MESSAGE = {
  //   CODE_REQUIRED: "Code is required",
  //   COMPANY_CODE_TOO_SHORT: "Company code must be at least 2 characters.",
  //   EMPLOYEE_CODE_REQUIRED: "Employee code is required",
  COUNTRY_CODE_IS_REQUIRED: "Country code is required",
  VALID_COUNTRY_CODE:
    "Country code must be exactly max 3 uppercase letters (e.g., 'IN', 'AUS').",
  STATE_CODE_IS_REQUIRED: "Code is required",
  STATE_NAME_IS_REQUIRED: "State name is required.",
  STATE_NAME_TOO_SHORT: "State name must be at least 4 characters.",
  VALID_STATE_CODE: "State code must be exactly 2 letters (e.g., 'HR', 'JK).",
  CITY_CODE_IS_REQUIRED: " City code is required",
  VALID_CITY_CODE: "City code must be exactly 2 digits (e.g., 'HR', 'CH).",
  INVALID_FORMAT: "Code format is invalid.",
  NAME_REQUIRED: "Name is required.",
  //   ROLE_NAME_REQUIRED: "Role Name is required",
  WRITE_MORE_THAN_THREE_CHARACTERS: "Please enter more than three characters.",
  WRITE_MORE_THAN_TWO_CHARACTERS: "Please enter more than two characters.",
  //   WRITE_MORE_THAN_HUNDERED_CHARACTERS: "Please enter more than 100 characters",
  //   WRITE_MORE_THAN_TWO_HUNDERED_CHARACTERS:
  //     "Please enter more than 200 characters",
  //   SELECT_MENU: "Select any One",
  //   CAPTION_IS_REQUIRED: "Caption is required",
  //   SELECT_FORM_MASTER: "Select form master",
  //   ICON_IS_REQUIRED: "Icon is required",
  //   FORM_MENU_GROUP: "Please Select a Form Menu Group",
  //   FORM_GROUP_IS_REQUIRED: "Form group is required",
  //   FORM_DISPLAY_NAME_IS_REQUIRED: "Form display name is required",
  //   FORM_NAME_IS_REQUIRED: "Form name is required",
  ITEM_NAME_IS_REQUIRED: "Item name is required.",
  ITEM_CODE_IS_REQUIRED: "Item code is required.",
  ITEM_CODE_TOO_SHORT: "Item code must be at lest 3 characters",
  UNIT_OF_MEASUREMENT_IS_REQUIRED: "Unit of measurement is required.",
  UOM_CODE_IS_REQUIRED: "Uom Code is required",
  UOM_CODE_IS_TOO_SHORT: "Uom code must be at least 2 characters.",
  UOM_NAME_IS_REQUIRED: "Uom Name is required",
  UOM_NAME_TOO_SHORT: "Uom name must be at least 2 characters.",
  //   ITEM_NAME_TOO_SHORT: "Item name must be at least 2 characters.",
  //   SELECT_PRIMARY_MENU: "Please select primary menu",
  //   SERIAL_NUMBER_REQUIRED: "Serial number is required",
  //   INVALID_MOBILE: "Please enter valid number",
  //   MOBILE_IS_REQUIRED: "Mobile is required",
  //   EMAIL_IS_REQUIRED: "Email is required",
  //   INVALID_EMAIL: "Please enter valid email",
  //   // created on 8 dec - priyanka 19 to end
  //   DATE_OF_BIRTH: "Date of birth is required",
  //   DATE_OF_ANNIVERSARY: "Date of Anniversary is required.",
  //   CORRECT_DOA_REQUIRED: "Please enter a valid date (MM-DD).",
  //   CORRECT_DOB_REQUIRED: "Enter Correct DOB",
  //   DATE_OF_JOINING: "Date of Joining is required.",
  //   CORRECT_DOJ_REQUIRED: "Please enter a valid Date of Joining.",
  //   FUTURE_DOJ_NOT_ALLOWED: "Future dates are not allowed for Date of Joining.",
  DESIGNATION_IS_REQUIRED: "Designation is required",
  DESIGNATION_CODE_IS_REQUIRED: "Designation code is required.",
  DESIGNATION_CODE_TOO_SHORT: "Designation code must be at least 2 characters.",
  DEPARTMENT_CODE_IS_REQUIRED: "Department code is required.",
  DEPARTMENT_CODE_TOO_SHORT: "Department code must be at least 2 characters.",
  DEPARTMENT_IS_REQUIRED: "Department Is Required",
  //   AGE_TOO_YOUNG: "Age must be at least 18 years.",
  //   AGE_TOO_OLD: "Age must be less than 70 years.",
  //   PRESENT_ADDRESS: "Present Address is required",
  //   PREMANENT_ADDRESS: "Permanent Address is required",
  COUNTRY_IS_REQUIRED: "Country is required",
  COUNTRY_NAME_IS_REQUIRED: "Country name is required.",
  COUNTRY_NAME_TOO_SHORT: "Country name must be at least 4 characters long.",
  CITY_NAME_TOO_SHORT: "City name must be at least 2 characters long.",
  STATE_IS_REQUIRED: "State is required",
  CITY_IS_REQUIRED: "City is required",
  //   LOGIN_TYPE_IS_REQUIRED: "Login type is required",
  SELECT_PROJECT: "Please select a project",
  LOCATION_IS_REQUIRED: "Location is required",
  PROJECT_NAME_IS_REQUIRED: "Project name is required",
  PROJECT_CODE_IS_REQUIRED: "Project code is required",
  SELECT_COMPANY: "Please select a company",

  //   USER_NAME_IS_REQUIRED: "User name is required",
  //   USER_ID_IS_REQUIRED: "User Id is required",
  //   PASSWORD_IS_REQUIRED: "Password is required",
  //   SETTING_NAME_IS_REQUIRED: "Setting name is required",
  //   SETTING_VALUE_IS_REQUIRED: "Setting value is required",
  //   SETTING_DESCRIPTION_IS_REQUIRED: "Setting description is required",
  //   FIELD_NAME_IS_REQUIRED: "Field name is required",
  TEMPLATE_IS_REQUIRED: "Template name is required,",
  //   DATA_TYPE_IS_REQUIRED: "Data type is required",
  //   FIELD_TYPE_IS_REQUIRED: "Field type is required",
  //   PINCODE_IS_REQUIRED: "Pincode is required",
  //   ENTER_VALID_PINCODE: "Please enter a valid 6-digit pin code.",
  //   FIELD_IS_REQUIRED: "Field is required",
  //   APPROVAL_TYPE_IS_REQUIRED: "Approval type is required",
  //   APPROVAL_NUMBER_IS_REQUIRED: "Approval number is required",
  //   APPROVAL_AUTHORITY_IS_REQUIRED: "Approval authority is required",
  COMPANY_NAME_IS_REQUIRED: "Company name is required",
  DISPLAY_NAME_IS_REQUIRED: "Display name is required",
  RIGHTS_COMPANY_IS_REQUIRED: "Rights company is required",
  LOGO_PATH_IS_REQUIRED: "Logo path is required",
  //   SUBJECT_AND_SCOPE_IS_REQUIRED: "Subject and scope Is Required",
  //   ENTER_ADDRESS: "Address is Required",
  //   DEPARTMENT_NAME_IS_REQUIRED: "Department name is required",
  //   REASON_OF_AMENDMENT_IS_REQUIRED: "Reason of amendment is required",
  //   APPROVAL_PRIORITY_IS_REQUIRED: "Approval Priority is required",
  //   URGENT_REMARK_IS_REQUIRED: "Urgent remark is required",
  //   AWARD_DATE_IS_REQUIRED: "Award date is required",
  //   APPROVAL_BUDGET_IS_REQUIRED: "Approval Budget is required",
  //   ALREADY_AWARDED_IS_REQUIRED: "Already Awarded is required",
  //   PROPOSED_VALUE_OF_AWARD_IS_REQUIRED: "Proposed value of award is required",
  //   BALANCE_TO_BE_AWARD_IS_REQUIRED: "Balance to be award is required",
  //   VARIATION_FROM_BUDGET_IS_REQUIRED: "Variation from budget is required",
  //   REASON_OF_VARIATION_IS_REQUIRED: "Reason of variation is required",
  DESCRIPTION_IS_REQUIRED: "Description is required",
  //   OTHER_DESCRIPTION_IS_REQUIRED: "Other Description is required",
  //   NAME_OF_PROPOSED_VENDOR_IS_REQUIRED: "Proposed vendor is required",
  //   NEGOTIATION_MODE_IS_REQUIRED: "Negotiation mode is required",
  //   VENDOR_CONSIDERED_IS_REQUIRED: "Vendor considered is required",
  //   REJECTED_VENDORS_IS_REQUIRED: "Rejected vendors is required",
  //   NOT_QUOTED_IS_REQUIRED: "Not quoted is required",
  //   STIPULATED_COMPLETION_TIME_IS_REQUIRED:
  //     "Stipulated completion time is required",
  //   SELECT_BID_TYPE: "Select bid type",
  //   SELECT_AUCTION_TYPE: "Select auction type",
  //   APPROVER_IS_REQUIRED: "Approver is required",
  //   UOM_REQUIRED: "UOM is required",
  //   SELECT_VENDOR_ONE: "Select vendor one",
  //   VENDORONE_DELIVERY_TIMELINE_IS_REQUIRED:
  //     "Please Enter Vendor 1 Delivery Timeline",
  //   VENDORONE_DELIVERY_BID_STATUS_IS_REQUIRED: "Please Enter Vendor 1 Bid Status",
  //   SELECT_VENDORONE_VENDOR_RATING: "Please Select Vendor 1 Vendor Ratings",
  //   SELECT_VENDORONE_PREFERENCE: "Please Select Vendor 1 Award Preference",
};

// end
